namespace: openshift-compliance

platform: generic

nodeSelector: null

tolerations: null

serviceAccounts:
  create: true
  accountNames:
    - compliance-operator
    - resultscollector
    - remediation-aggregator
    - rerunner
    - api-resource-collector
    - profileparser
    - resultserver

scanSettingBindings:
  create: false
  Bindings:
    - bindingName: nist-moderate
      profileName: rhcos4-moderate
      scanSettingName: default
